In [2]:
import numpy as np
#2D
np.array([[1,2,3],[4,5,6]])
# 3D
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
#dtype
np.array([1,2,3],dtype="float")
np.array([1.2 ,2.3],dtype="int")
np.array([1,2,3],dtype="complex")


array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
#arrange
np.arange(1,11)
# with slicing
np.arange(1,11,2)
# it steps upto 2 elemnts

array([1, 3, 5, 7, 9])

In [10]:
# with reshape
np.arange(1,11).reshape(5,2)
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
# np.ones and zeroes
np.ones((3,4),dtype="complex")
#np.zeros((3,4) ,dtype="int")

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [23]:
np.random.random((3,4))

array([[0.82413416, 0.02366296, 0.52071169, 0.73098522],
       [0.31552927, 0.50347095, 0.28298512, 0.8924659 ],
       [0.67451305, 0.33711805, 0.31190321, 0.41136667]])

In [24]:
#np.linspace
np.linspace(10,-10,10)

array([ 10.        ,   7.77777778,   5.55555556,   3.33333333,
         1.11111111,  -1.11111111,  -3.33333333,  -5.55555556,
        -7.77777778, -10.        ])

In [28]:
np.identity(3)
#np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
a1=np.arange(10 , dtype = "int32")
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [33]:
#ndim
a3.ndim
#shape
a3.shape
a3.size
# no of elemnts = size

8

In [40]:
# item size
#a3.itemsize
#a2.itemsize
a1.itemsize
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


# Changing the datatype


In [43]:
#as type
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [45]:
# we can any mathematical operations in numpy
a1 = np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [50]:
# SCALERR OPEARTIONS
# arthimetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [52]:
#relational
a1>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [55]:
# VECTOR OPERATONS
# arthemetic operation
a1 + a2
a1/a2
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [64]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*10)
print(a1)


[[0.49042784 0.93316072 0.80231873]
 [0.4526036  0.69387577 0.05903567]
 [0.95300298 0.50923836 0.0519971 ]]
[[ 5.  9.  8.]
 [ 5.  7.  1.]
 [10.  5.  1.]]


In [68]:
# max /min /prod/sum
np.max(a1)
np.min(a1)
np.prod(a1)
np.sum(a1)


np.float64(51.0)

# 0 -> column
# 1 ->row

In [76]:
#np.min(a1,axis=0)
#np.min(a1,axis=1)
#np.max(a1,axis=0)
np.max(a1,axis=1)

array([ 9.,  7., 10.])

In [78]:
#mean/ median /std/ var
np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis =1)


array([ 2.88888889,  6.22222222, 13.55555556])

In [79]:
# trigo function
np.sin(a1)

array([[-0.95892427,  0.41211849,  0.98935825],
       [-0.95892427,  0.6569866 ,  0.84147098],
       [-0.54402111, -0.95892427,  0.84147098]])

In [80]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exponents
np.exp(a1)

array([[1.48413159e+02, 8.10308393e+03, 2.98095799e+03],
       [1.48413159e+02, 1.09663316e+03, 2.71828183e+00],
       [2.20264658e+04, 1.48413159e+02, 2.71828183e+00]])

In [84]:
# round/floor /ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((3,4))*100)
np.ceil(np.random.random((3,4))*100)

array([[22., 76.,  3., 98.],
       [87., 19., 58., 43.],
       [44., 42., 57., 14.]])

# Indexing and slicing


In [89]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3=  np.arange(8).reshape(2,2,2)

In [91]:
a1
a1[-1]

np.int64(9)

In [94]:
a2
#a2[1:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a2[1,2]

np.int64(6)

In [108]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
a3[1,0,1]
a3[0,1,0]
a3[1,1,0]

np.int64(6)

In [113]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
a1[2:5:2]

array([2, 4])

In [115]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
a2[0,:]

array([0, 1, 2, 3])

In [118]:
a2[:,0]

array([0, 4, 8])

In [120]:
a2[1:,1:3]
# rows alternate
# columns double alternate
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
# 1,3 -- 9,11
a2[::2,1::2]
#4,7
a2[1,::3]

array([4, 7])

In [126]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [130]:
a3[1,0:,]
a3[1]
a3[::2,]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# iterating
