In [3]:
import numpy as np
#2D
np.array([[1,2,3],[4,5,6]])
# 3D
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
#dtype
np.array([1,2,3],dtype="float")
np.array([1.2 ,2.3],dtype="int")
np.array([1,2,3],dtype="complex")


array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
#arrange
np.arange(1,11)
# with slicing
np.arange(1,11,2)
# it steps upto 2 elemnts

array([1, 3, 5, 7, 9])

In [5]:
# with reshape
np.arange(1,11).reshape(5,2)
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# np.ones and zeroes
np.ones((3,4),dtype="complex")
#np.zeros((3,4) ,dtype="int")

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [7]:
np.random.random((3,4))

array([[0.32940456, 0.63292223, 0.83910825, 0.7693043 ],
       [0.83368136, 0.44630735, 0.62759563, 0.19902131],
       [0.37479109, 0.77500366, 0.51266403, 0.60285625]])

In [8]:
#np.linspace
np.linspace(10,-10,10)

array([ 10.        ,   7.77777778,   5.55555556,   3.33333333,
         1.11111111,  -1.11111111,  -3.33333333,  -5.55555556,
        -7.77777778, -10.        ])

In [9]:
np.identity(3)
#np.arange(8).reshape(2,2,2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
a1=np.arange(10 , dtype = "int32")
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [11]:
#ndim
a3.ndim
#shape
a3.shape
a3.size
# no of elemnts = size

8

In [12]:
# item size
#a3.itemsize
#a2.itemsize
a1.itemsize
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


# Changing the datatype


In [13]:
#as type
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [14]:
# we can any mathematical operations in numpy
a1 = np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [50]:
# SCALERR OPEARTIONS
# arthimetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [15]:
#relational
a1>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [16]:
# VECTOR OPERATONS
# arthemetic operation
a1 + a2
a1/a2
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [64]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*10)
print(a1)


[[0.49042784 0.93316072 0.80231873]
 [0.4526036  0.69387577 0.05903567]
 [0.95300298 0.50923836 0.0519971 ]]
[[ 5.  9.  8.]
 [ 5.  7.  1.]
 [10.  5.  1.]]


In [17]:
# max /min /prod/sum
np.max(a1)
np.min(a1)
np.prod(a1)
np.sum(a1)


np.int64(66)

# 0 -> column
# 1 ->row

In [18]:
#np.min(a1,axis=0)
#np.min(a1,axis=1)
#np.max(a1,axis=0)
np.max(a1,axis=1)

array([ 3,  7, 11])

In [19]:
#mean/ median /std/ var
np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis =1)


array([1.25, 1.25, 1.25])

In [20]:
# trigo function
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [21]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [22]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [23]:
# round/floor /ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((3,4))*100)
np.ceil(np.random.random((3,4))*100)

array([[67., 80., 59., 20.],
       [19., 63., 74., 91.],
       [53., 34., 72., 65.]])

# Indexing and slicing


In [25]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3=  np.arange(8).reshape(2,2,2)

In [26]:
a1
a1[-1]

np.int64(9)

In [27]:
a2
#a2[1:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a2[1,2]

np.int64(6)

In [108]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
a3[1,0,1]
a3[0,1,0]
a3[1,1,0]

np.int64(6)

In [30]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1[2:5:2]

array([2, 4])

In [115]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a2[0,:]

array([0, 1, 2, 3])

In [33]:
a2[:,0]

array([0, 4, 8])

In [34]:
a2[1:,1:3]
# rows alternate
# columns double alternate
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [35]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
# 1,3 -- 9,11
a2[::2,1::2]
#4,7
a2[1,::3]

array([4, 7])

In [37]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
a3[1,0:,]
a3[1]
a3[::2,]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# iterating


In [39]:

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])