In [ ]:
import numpy as np
#2D
np.array([[1,2,3],[4,5,6]])
# 3D
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
#dtype
np.array([1,2,3],dtype="float")
np.array([1.2 ,2.3],dtype="int")
np.array([1,2,3],dtype="complex")


In [ ]:
#arrange
np.arange(1,11)
# with slicing
np.arange(1,11,2)
# it steps upto 2 elemnts

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)
np.arange(1,11).reshape(2,5)

In [ ]:
# np.ones and zeroes
np.ones((3,4),dtype="complex")
#np.zeros((3,4) ,dtype="int")

In [ ]:
np.random.random((3,4))

In [ ]:
#np.linspace
np.linspace(10,-10,10)

In [ ]:
np.identity(3)
#np.arange(8).reshape(2,2,2)

In [ ]:
a1=np.arange(10 , dtype = "int32")
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [ ]:
#ndim
a3.ndim
#shape
a3.shape
a3.size
# no of elemnts = size

In [ ]:
# item size
#a3.itemsize
#a2.itemsize
a1.itemsize
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


# Changing the datatype


In [ ]:
#as type
a3.dtype
a3.astype(np.int32)

# Array Operations

In [ ]:
# we can any mathematical operations in numpy
a1 = np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [ ]:
# SCALERR OPEARTIONS
# arthimetic
a1 ** 2

In [ ]:
#relational
a1>10

In [ ]:
# VECTOR OPERATONS
# arthemetic operation
a1 + a2
a1/a2
a1 - a2

In [ ]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*10)
print(a1)


In [ ]:
# max /min /prod/sum
np.max(a1)
np.min(a1)
np.prod(a1)
np.sum(a1)


# 0 -> column
# 1 ->row

In [ ]:
#np.min(a1,axis=0)
#np.min(a1,axis=1)
#np.max(a1,axis=0)
np.max(a1,axis=1)

In [ ]:
#mean/ median /std/ var
np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis =1)


In [ ]:
# trigo function
np.sin(a1)

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

In [ ]:
# log and exponents
np.exp(a1)

In [ ]:
# round/floor /ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((3,4))*100)
np.ceil(np.random.random((3,4))*100)

# Indexing and slicing


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3=  np.arange(8).reshape(2,2,2)

In [ ]:
a1
a1[-1]

In [ ]:
a2
#a2[1:3]

In [ ]:
a2[1,2]

In [ ]:
a3


In [ ]:
a3[1,0,1]
a3[0,1,0]
a3[1,1,0]

In [ ]:
a1


In [ ]:
a1[2:5:2]

In [ ]:
a2


In [ ]:
a2[0,:]

In [ ]:
a2[:,0]

In [ ]:
a2[1:,1:3]
# rows alternate
# columns double alternate
a2[::2,::3]

In [ ]:
a2

In [ ]:
# 1,3 -- 9,11
a2[::2,1::2]
#4,7
a2[1,::3]

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

In [ ]:
a3[1,0:,]
a3[1]
a3[::2,]

# iterating


In [ ]:

a1

In [ ]:
for i in a1 :
    print(i)

In [ ]:
a3

In [43]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
